/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/position/greeks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compute aggregated Greeks for a multi-leg position */
        post: operations["position_greeks_position_greeks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/position/leg-prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Per-share model price for each leg (per-leg IV respected)
         * @description Returns one per-share price per leg, in the input order. Multiply by
         *     100 × leg.quantity to get the per-leg cost / credit in dollars.
         *     Stock legs price at spot; option legs use their own IV when set.
         */
        post: operations["position_leg_prices_position_leg_prices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/position/payoff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Payoff curve (today + at expiry) over a spot range */
        post: operations["position_payoff_position_payoff_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/position/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scenario simulator: P&L with Greek decomposition */
        post: operations["position_simulate_position_simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chain/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Spot price and available expiry dates for a ticker */
        get: operations["chain_meta_chain__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chain/{ticker}/{expiry}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full option chain (calls + puts) for a ticker at one expiry */
        get: operations["chain_full_chain__ticker___expiry__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ticker/{ticker}/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One-call snapshot: spot, expiries with DTE, and ATM-call IV
         * @description Wraps `chain_meta` + `chain_full` into one tidy payload for the frontend.
         *     If `expiry` is omitted, uses the nearest available expiry to source ATM IV.
         */
        get: operations["ticker_snapshot_ticker__ticker__snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Free-form Q&A about the current position. Tool-augmented (calls the simulator). */
        post: operations["chat_endpoint_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service identity */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChainMetaOut */
        ChainMetaOut: {
            /** Ticker */
            ticker: string;
            /** Spot */
            spot: number;
            /** Expiries */
            expiries: string[];
            /** As Of */
            as_of: string;
        };
        /** ChainOut */
        ChainOut: {
            /** Ticker */
            ticker: string;
            /** Spot */
            spot: number;
            /** Expiry */
            expiry: string;
            /** As Of */
            as_of: string;
            /** Calls */
            calls: components["schemas"]["ChainRow"][];
            /** Puts */
            puts: components["schemas"]["ChainRow"][];
        };
        /** ChainRow */
        ChainRow: {
            /** Strike */
            strike: number;
            /** Bid */
            bid: number;
            /** Ask */
            ask: number;
            /** Mid */
            mid: number;
            /** Last */
            last: number;
            /** Volume */
            volume: number;
            /** Open Interest */
            open_interest: number;
            /** Iv */
            iv: number;
        };
        /** ChatMessage */
        ChatMessage: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Messages */
            messages: components["schemas"]["ChatMessage"][];
            position: components["schemas"]["PositionIn"];
        };
        /** ChatResponse */
        ChatResponse: {
            /**
             * Role
             * @default assistant
             * @constant
             */
            role: "assistant";
            /** Content */
            content: string;
            /** Tool Uses */
            tool_uses?: components["schemas"]["ChatToolUse"][];
            /** Rate Used */
            rate_used: number;
        };
        /** ChatToolUse */
        ChatToolUse: {
            /** Name */
            name: string;
            /** Input */
            input: {
                [key: string]: unknown;
            };
            /** Output */
            output?: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error?: string | null;
        };
        /** ExpiryItem */
        ExpiryItem: {
            /** Date */
            date: string;
            /** Days To Expiry */
            days_to_expiry: number;
        };
        /** GreeksOut */
        GreeksOut: {
            /** Price */
            price: number;
            /** Delta */
            delta: number;
            /** Gamma */
            gamma: number;
            /** Theta Per Day */
            theta_per_day: number;
            /** Vega Per Volpoint */
            vega_per_volpoint: number;
            /** Rho Per Pct */
            rho_per_pct: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LegIn */
        LegIn: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "call" | "put" | "stock";
            /**
             * Strike
             * @description ignored for stock legs
             * @default 0
             */
            strike: number;
            /**
             * Expiry Days
             * @description calendar days from position-open; ignored for stock legs
             * @default 0
             */
            expiry_days: number;
            /**
             * Quantity
             * @description contracts (1 = 100 shares); negative = short
             */
            quantity: number;
            /**
             * Sigma
             * @description per-leg IV override in decimal (0.22 = 22%); falls back to position sigma
             */
            sigma?: number | null;
            /**
             * Entry Price
             * @description actual fill per share; affects cost basis only. Defaults to model price.
             */
            entry_price?: number | null;
        };
        /**
         * LegPricesOut
         * @description Per-share Black-Scholes price for each leg, in the same order as input.
         */
        LegPricesOut: {
            /** Prices */
            prices: number[];
        };
        /** PayoffOut */
        PayoffOut: {
            /** Initial Value */
            initial_value: number;
            /** Cost Basis */
            cost_basis: number;
            /** Points */
            points: components["schemas"]["PayoffPoint"][];
        };
        /** PayoffPoint */
        PayoffPoint: {
            /** Spot */
            spot: number;
            /** Pnl Today */
            pnl_today: number;
            /** Pnl At Expiry */
            pnl_at_expiry: number;
        };
        /** PayoffRequest */
        PayoffRequest: {
            position: components["schemas"]["PositionIn"];
            /**
             * Spot Min
             * @description defaults to S * 0.9
             */
            spot_min?: number | null;
            /**
             * Spot Max
             * @description defaults to S * 1.1
             */
            spot_max?: number | null;
            /**
             * Num Points
             * @default 201
             */
            num_points: number;
        };
        /** PositionIn */
        PositionIn: {
            /**
             * S
             * @description spot price at position creation
             */
            S: number;
            /**
             * Sigma
             * @description IV in decimal (0.20 = 20%)
             */
            sigma: number;
            /**
             * R
             * @description risk-free rate in decimal
             */
            r: number;
            /** Legs */
            legs: components["schemas"]["LegIn"][];
        };
        /** SimulateOut */
        SimulateOut: {
            /** Actual Pnl */
            actual_pnl: number;
            /** Delta Contribution */
            delta_contribution: number;
            /** Gamma Contribution */
            gamma_contribution: number;
            /** Theta Contribution */
            theta_contribution: number;
            /** Vega Contribution */
            vega_contribution: number;
            /** Sum Of Components */
            sum_of_components: number;
            /** Residual */
            residual: number;
            initial_greeks: components["schemas"]["GreeksOut"];
            new_greeks: components["schemas"]["GreeksOut"];
        };
        /** SimulateRequest */
        SimulateRequest: {
            position: components["schemas"]["PositionIn"];
            /**
             * Ds
             * @description change in spot ($)
             * @default 0
             */
            dS: number;
            /**
             * Dsigma
             * @description change in IV decimal (-0.01 = -1 vol-pt)
             * @default 0
             */
            dSigma: number;
            /**
             * Ddays
             * @default 0
             */
            dDays: number;
        };
        /**
         * TickerSnapshotOut
         * @description One-call payload for the frontend: spot, available expiries (with DTE
         *     pre-computed), and the ATM-call implied vol for the nearest expiry.
         */
        TickerSnapshotOut: {
            /** Ticker */
            ticker: string;
            /** Spot */
            spot: number;
            /** As Of */
            as_of: string;
            /** Expiries */
            expiries: components["schemas"]["ExpiryItem"][];
            /** Atm Expiry */
            atm_expiry?: string | null;
            /** Atm Strike */
            atm_strike?: number | null;
            /** Atm Iv */
            atm_iv?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    position_greeks_position_greeks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PositionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GreeksOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    position_leg_prices_position_leg_prices_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PositionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegPricesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    position_payoff_position_payoff_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PayoffRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PayoffOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    position_simulate_position_simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chain_meta_chain__ticker__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChainMetaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chain_full_chain__ticker___expiry__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
                expiry: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChainOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ticker_snapshot_ticker__ticker__snapshot_get: {
        parameters: {
            query?: {
                expiry?: string | null;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TickerSnapshotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_endpoint_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
