/**
 * Typed API client for the Greeks Education backend.
 *
 * Types come from `api-types.ts` (auto-generated by `openapi-typescript`
 * against the FastAPI /openapi.json spec). Regenerate with:
 *
 *   npx openapi-typescript http://127.0.0.1:8000/openapi.json -o src/lib/api-types.ts
 */
import type { paths } from "./api-types";

const BASE_URL =
  process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://127.0.0.1:8000";

// ── Request / response types (pulled from generated schema) ──
export type Position =
  paths["/position/greeks"]["post"]["requestBody"]["content"]["application/json"];
export type Greeks =
  paths["/position/greeks"]["post"]["responses"]["200"]["content"]["application/json"];

export type SimulateRequest =
  paths["/position/simulate"]["post"]["requestBody"]["content"]["application/json"];
export type SimulateResponse =
  paths["/position/simulate"]["post"]["responses"]["200"]["content"]["application/json"];

export type PayoffRequest =
  paths["/position/payoff"]["post"]["requestBody"]["content"]["application/json"];
export type PayoffResponse =
  paths["/position/payoff"]["post"]["responses"]["200"]["content"]["application/json"];

export type TickerSnapshot =
  paths["/ticker/{ticker}/snapshot"]["get"]["responses"]["200"]["content"]["application/json"];
export type ExpiryItem = TickerSnapshot["expiries"][number];

export type ChainFull =
  paths["/chain/{ticker}/{expiry}"]["get"]["responses"]["200"]["content"]["application/json"];
export type ChainRow = ChainFull["calls"][number];

export type ChatRequest =
  paths["/chat"]["post"]["requestBody"]["content"]["application/json"];
export type ChatResponse =
  paths["/chat"]["post"]["responses"]["200"]["content"]["application/json"];
export type ChatMessage = ChatRequest["messages"][number];

export type LegPrices =
  paths["/position/leg-prices"]["post"]["responses"]["200"]["content"]["application/json"];

// ── Tiny fetch wrapper ──
async function postJSON<T>(path: string, body: unknown): Promise<T> {
  const res = await fetch(`${BASE_URL}${path}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`API ${path} → ${res.status}: ${text}`);
  }
  return res.json() as Promise<T>;
}

async function getJSON<T>(path: string): Promise<T> {
  const res = await fetch(`${BASE_URL}${path}`);
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`API ${path} → ${res.status}: ${text}`);
  }
  return res.json() as Promise<T>;
}

// ── Public API ──
export const api = {
  positionGreeks: (body: Position) =>
    postJSON<Greeks>("/position/greeks", body),
  positionPayoff: (body: PayoffRequest) =>
    postJSON<PayoffResponse>("/position/payoff", body),
  positionSimulate: (body: SimulateRequest) =>
    postJSON<SimulateResponse>("/position/simulate", body),
  positionLegPrices: (body: Position) =>
    postJSON<LegPrices>("/position/leg-prices", body),
  tickerSnapshot: (ticker: string) =>
    getJSON<TickerSnapshot>(`/ticker/${encodeURIComponent(ticker)}/snapshot`),
  chainFull: (ticker: string, expiry: string) =>
    getJSON<ChainFull>(
      `/chain/${encodeURIComponent(ticker)}/${encodeURIComponent(expiry)}`,
    ),
  chat: (body: ChatRequest) =>
    postJSON<ChatResponse>("/chat", body),
};
